version: '3.7'
services:
  yarn:
    build: .
    init: true
    volumes:
      - .:/application
      - yarn-cache:/root/.cache/yarn/v1
    entrypoint: yarn

volumes:
  yarn-cache:
    name: yarn-cache
